dataset_type: resynth
stage: coarse
batch_size: 4
save_all_results: 0
data_spacing: 1
epochs: 151
query_posmap_size: 128
inp_posmap_size: 128
mode: train
transf_scaling: 0.02
use_vert_geom_feat: 0
actv_fn: softplus
query_xyz: 1
use_jT: 1
incl_query_nml: 1
pos_encoding: 1 
num_emb_freqs: 6
use_global_geom_feat: 1
c_geom: 256