dataset_type: resynth
stage: fine
batch_size: 4
save_all_results: 1
data_spacing: 1
epochs: 251
query_posmap_size: 256
inp_posmap_size: 128
mode: train
use_vert_geom_feat: 0
pose_feat_type: conv
actv_fn: softplus
use_pose_emb: 0
query_xyz: 0
use_jT: 1
incl_query_nml: 0
pos_encoding: 0
num_emb_freqs: 10 
eval_body_verts: 0
transf_scaling: 0.02
w_lbsw: 0.0
adaptive_lbsw_weight_in_training: 1
start_adaptive_at: 10
incl_query_nml: 1
transf_only_disp: 0
pred_lbsw: 1
two_stage_training: 1
vol_lbsw_thres: 0.0
use_pre_diffuse_lbsw: 1